# Generated by Django 6.1.1 on 2026-09-18 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scenario', models.CharField(choices=[('competition', '学科竞赛'), ('research', '科研课题'), ('coding', '代码调试'), ('gpa', '绩点焦虑'), ('exam', '备考压力'), ('setback', '学业受挫'), ('general', '一般压力')], default='general', max_length=20)),
                ('initial_stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_stress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('action_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '匿名成效记录',
                'verbose_name_plural': '匿名成效记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
