# Generated by Django 6.1.1 on 2026-09-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomerecord',
            name='actionable_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcomerecord',
            name='feedback_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='outcomerecord',
            name='helpful_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcomerecord',
            name='return_intent_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outcomerecord',
            name='understood_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
