# Generated by Django 6.1.1 on 2026-09-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_outcomerecord_actionable_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomerecord',
            name='evidence_approved',
            field=models.BooleanField(default=False, verbose_name='已核验并纳入成效统计'),
        ),
        migrations.AddField(
            model_name='outcomerecord',
            name='evidence_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
    ]
